'use client'

import { useState, useEffect } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Download, Play, Edit, FileText, ChevronRight, ChevronLeft } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import ZAISlideGenerator from '@/components/ZAISlideGenerator'

interface Slide {
  id: string
  title: string
  content: string[]
  type: 'title' | 'content' | 'bullet' | 'image' | 'quote'
  layout: 'center' | 'left' | 'right' | 'two-column'
  notes?: string
}

interface Presentation {
  id: string
  title: string
  description: string
  slides: Slide[]
  theme: string
  createdAt: string
  updatedAt: string
  isZAI?: boolean
  slide_urls?: string[]
  download_urls?: string[]
  version?: number
}

interface Course {
  id: string
  name: string
  subject: string
}

type ZAISlideGeneration = {
  id: string
  topic: string
  generation_method: string
  slide_urls: string[]
  style: string
  created_at: string
  download_urls?: string[]
  version?: number
}

type SlidesListResponse = {
  slides?: ZAISlideGeneration[]
}

type GeneratedSlide = {
  topic?: string
  title?: string
  slide_urls?: string[]
  download_urls?: string[]
}

const presentationThemes = [
  { id: 'modern', name: 'Moderno', colors: ['#1f2937', '#3b82f6', '#10b981'] },
  { id: 'academic', name: 'Accademico', colors: ['#1e40af', '#1e3a8a', '#dc2626'] },
  { id: 'creative', name: 'Creativo', colors: ['#7c3aed', '#ec4899', '#f59e0b'] },
  { id: 'minimal', name: 'Minimale', colors: ['#111827', '#6b7280', '#f3f4f6'] },
]

const slideTemplates = [
  { id: 'title', name: 'Titolo', icon: '📊', description: 'Slide con titolo grande e sottotitolo' },
  { id: 'content', name: 'Contenuto', icon: '📝', description: 'Slide con testo e contenuti' },
  { id: 'bullet', name: 'Punti Elenco', icon: '📋', description: 'Slide con elenco puntato' },
  { id: 'image', name: 'Immagine', icon: '🖼️', description: 'Slide con immagine e testo' },
  { id: 'quote', name: 'Citazione', icon: '💬', description: 'Slide con citazione importante' },
]

export default function SlidesPage() {
  const params = useParams()
  const courseId = params.id as string

  const [course, setCourse] = useState<Course | null>(null)
  const [presentations, setPresentations] = useState<Presentation[]>([])
  const [currentPresentation, setCurrentPresentation] = useState<Presentation | null>(null)
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0)
  const [loading, setLoading] = useState(true)
  const [showPreview, setShowPreview] = useState(false)

  useEffect(() => {
    fetchCourse()
    fetchPresentations()
  }, [courseId])

  const fetchCourse = async () => {
    try {
      const response = await fetch(`/api/courses/${courseId}`)
      if (response.ok) {
        const data = await response.json()
        setCourse(data.course)
      }
    } catch (error) {
      console.error('Error fetching course:', error)
    }
  }

  const fetchPresentations = async () => {
    try {
      // Fetch new Z.AI slide generations
      const newResponse = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}/slides/list?course_id=${courseId}&limit=20`)
      const slidesPayload: SlidesListResponse = newResponse.ok ? await newResponse.json() : {}
      const newPresentations = Array.isArray(slidesPayload.slides) ? slidesPayload.slides : []

      // Convert Z.AI slides to presentation format
      const convertedPresentations = newPresentations.map((slide) => ({
        id: slide.id,
        title: slide.topic,
        description: `Generated by ${slide.generation_method}`,
        slides: slide.slide_urls.map((url: string, index: number) => ({
          id: `slide-${index}`,
          title: `Slide ${index + 1}`,
          content: [url],
          type: 'image' as const,
          layout: 'center' as const,
          notes: `Generated slide image`
        })),
        theme: slide.style,
        createdAt: slide.created_at,
        updatedAt: slide.created_at,
        isZAI: true,
        slide_urls: slide.slide_urls,
        download_urls: slide.download_urls,
        version: slide.version
      }))

      // Sort by creation date (newest first)
      convertedPresentations.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())

      setPresentations(convertedPresentations)
    } catch (error) {
      console.error('Error fetching presentations:', error)
    } finally {
      setLoading(false)
    }
  }

  const addSlide = (templateId: string) => {
    if (!currentPresentation) return

    const newSlide: Slide = {
      id: `slide-${Date.now()}`,
      title: 'Nuova Slide',
      content: [],
      type: templateId as Slide['type'],
      layout: 'center'
    }

    const updatedPresentation = {
      ...currentPresentation,
      slides: [...currentPresentation.slides, newSlide],
      updatedAt: new Date().toISOString()
    }

    setCurrentPresentation(updatedPresentation)
    setCurrentSlideIndex(updatedPresentation.slides.length - 1)
  }

  const exportPresentation = async () => {
    if (!currentPresentation) return

    if (currentPresentation.isZAI && currentPresentation.id) {
      try {
        // Download unified PDF from backend
        const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}/slides/download/${currentPresentation.id}`)

        if (!response.ok) {
          throw new Error('Failed to generate PDF')
        }

        const data = await response.json()

        if (data.success && data.pdf_url) {
          // Create download link for unified PDF
          const link = document.createElement('a')
          link.href = data.pdf_url
          link.download = data.filename
          link.target = '_blank'
          document.body.appendChild(link)
          link.click()
          document.body.removeChild(link)

          alert(`Downloading unified PDF: ${data.filename} (${Math.round(data.size / 1024)}KB)`)
        } else {
          throw new Error('Invalid response from server')
        }
      } catch (error) {
        console.error('Error downloading PDF:', error)
        alert('Failed to download PDF. Please try again.')
      }
    } else {
      // Export as JSON for old presentations
      const presentationData = {
        ...currentPresentation,
        theme: presentationThemes.find(t => t.id === currentPresentation.theme)
      }

      const blob = new Blob([JSON.stringify(presentationData, null, 2)], { type: 'application/json' })
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${currentPresentation.title.replace(/\s+/g, '_')}.json`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      window.URL.revokeObjectURL(url)
    }
  }

  const currentSlide = currentPresentation?.slides[currentSlideIndex]

  if (loading) {
    return (
      <div className="flex justify-center items-center min-h-[60vh]">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin mx-auto"></div>
          <p className="mt-4 text-gray-600">Caricamento...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container-responsive py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center space-x-4 mb-4">
            <Link
              href={`/courses/${courseId}`}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
            >
              <ArrowLeft className="h-5 w-5 text-gray-600" />
            </Link>
            <div className="flex-1">
              <nav className="text-sm text-gray-500 mb-2">
                <Link href={`/courses/${courseId}`} className="hover:text-gray-700">
                  {course?.name}
                </Link>
                <span className="mx-2">/</span>
                <span className="text-gray-900">Generatore Slide</span>
              </nav>
              <h1 className="text-3xl font-bold text-gray-900">Generatore di Slide AI</h1>
              <p className="text-gray-600 mt-1">Crea presentazioni professionali dai tuoi materiali di studio</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left Panel - Generation Controls */}
          <div className="lg:col-span-1 space-y-6">
            {/* ZAI Agent Generation Form */}
            <div className="bg-white rounded-xl shadow-sm border p-6">
              <ZAISlideGenerator
                courseId={courseId}
                onSlidesGenerated={(slides: GeneratedSlide[]) => {
                  if (slides.length > 0) {
                    // Convert slides to presentation format
                    const newPresentation: Presentation = {
                      id: `zai-${Date.now()}`,
                      title: slides[0]?.topic || 'New Z.AI Presentation',
                      description: 'Generated by Z.AI GLM Slide Agent',
                      slides: slides.map((slide, index) => ({
                        id: `slide-${index}`,
                        title: slide.topic || slide.title || `Slide ${index + 1}`,
                        content: slide.slide_urls || [],
                        type: 'image' as const,
                        layout: 'center' as const,
                        notes: `Generated by Z.AI`
                      })),
                      theme: 'modern',
                      createdAt: new Date().toISOString(),
                      updatedAt: new Date().toISOString(),
                      isZAI: true,
                      slide_urls: slides[0]?.slide_urls || [],
                      download_urls: slides[0]?.download_urls || []
                    }
                    setCurrentPresentation(newPresentation)
                    setCurrentSlideIndex(0)
                    setShowPreview(true)
                  }
                }}
              />
            </div>

            {/* Slide Templates */}
            {currentPresentation && (
              <div className="bg-white rounded-xl shadow-sm border p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Aggiungi Slide</h3>
                <div className="grid grid-cols-2 gap-2">
                  {slideTemplates.map(template => (
                    <button
                      key={template.id}
                      onClick={() => addSlide(template.id)}
                      className="p-3 rounded-lg border border-gray-200 hover:border-purple-300 hover:bg-purple-50 transition-all text-left"
                    >
                      <div className="text-lg mb-1">{template.icon}</div>
                      <div className="text-sm font-medium text-gray-900">{template.name}</div>
                      <div className="text-xs text-gray-600 mt-1">{template.description}</div>
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Existing Presentations */}
            {presentations.length > 0 && (
              <div className="bg-white rounded-xl shadow-sm border p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Presentazioni Esistenti</h3>
                <div className="space-y-2">
                  {presentations.map(presentation => (
                    <button
                      key={presentation.id}
                      onClick={() => {
                        setCurrentPresentation(presentation)
                        setCurrentSlideIndex(0)
                        setShowPreview(true)
                      }}
                      className="w-full p-3 rounded-lg border border-gray-200 hover:border-purple-300 hover:bg-purple-50 transition-all text-left"
                    >
                      <div className="flex items-center justify-between">
                        <div className="font-medium text-gray-900">{presentation.title}</div>
                        {presentation.isZAI && (
                          <span className="text-xs bg-purple-100 text-purple-800 px-2 py-1 rounded">
                            Z.AI
                          </span>
                        )}
                      </div>
                      <div className="text-sm text-gray-600">
                        {presentation.slides.length} slide • {new Date(presentation.createdAt).toLocaleDateString()}
                        {presentation.version && (
                          <span className="ml-2 text-xs bg-gray-100 text-gray-800 px-2 py-1 rounded">
                            v{presentation.version}
                          </span>
                        )}
                      </div>
                      {presentation.isZAI && (
                        <div className="text-xs text-green-600 mt-1">
                          🎨 Generated with Z.AI GLM Slide Agent
                        </div>
                      )}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Right Panel - Preview & Editor */}
          <div className="lg:col-span-2">
            {currentPresentation && showPreview ? (
              <div className="bg-white rounded-xl shadow-sm border">
                {/* Presentation Header */}
                <div className="p-6 border-b">
                  <div className="flex items-center justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <h2 className="text-xl font-bold text-gray-900">{currentPresentation.title}</h2>
                        {currentPresentation.isZAI && (
                          <span className="text-xs bg-purple-100 text-purple-800 px-2 py-1 rounded">
                            Z.AI GLM Slide Agent
                          </span>
                        )}
                        {currentPresentation.version && (
                          <span className="text-xs bg-gray-100 text-gray-800 px-2 py-1 rounded">
                            Version {currentPresentation.version}
                          </span>
                        )}
                      </div>
                      <p className="text-gray-600 mt-1">{currentPresentation.description}</p>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Button
                        onClick={() => setShowPreview(false)}
                        variant="secondary"
                        size="sm"
                      >
                        <Edit className="h-4 w-4 mr-2" />
                        Modifica
                      </Button>
                      <Button
                        onClick={exportPresentation}
                        variant="secondary"
                        size="sm"
                      >
                        <Download className="h-4 w-4 mr-2" />
                        Esporta
                      </Button>
                      <Button size="sm">
                        <Play className="h-4 w-4 mr-2" />
                        Presenta
                      </Button>
                    </div>
                  </div>
                </div>

                {/* Slide Viewer */}
                <div className="p-6">
                  <div className="bg-gradient-to-br from-gray-50 to-gray-100 rounded-xl p-8 min-h-[500px]">
                    {currentSlide && (
                      <div>
                        {/* Slide Header */}
                        <div className="flex items-center justify-between mb-6">
                          <div className="text-sm text-gray-600">
                            Slide {currentSlideIndex + 1} di {currentPresentation.slides.length}
                          </div>
                          <div className="flex items-center space-x-2">
                            <button
                              onClick={() => setCurrentSlideIndex(Math.max(0, currentSlideIndex - 1))}
                              disabled={currentSlideIndex === 0}
                              className="p-2 rounded-lg border border-gray-300 hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                              <ChevronLeft className="h-4 w-4" />
                            </button>
                            <button
                              onClick={() => setCurrentSlideIndex(Math.min(currentPresentation.slides.length - 1, currentSlideIndex + 1))}
                              disabled={currentSlideIndex === currentPresentation.slides.length - 1}
                              className="p-2 rounded-lg border border-gray-300 hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                              <ChevronRight className="h-4 w-4" />
                            </button>
                          </div>
                        </div>

                        {/* Slide Content */}
                        <div className="bg-white rounded-lg shadow-lg p-8">
                          {currentSlide.type === 'title' && (
                            <div className="text-center">
                              <h1 className="text-4xl font-bold text-gray-900 mb-4">
                                {currentSlide.title || 'Titolo della Slide'}
                              </h1>
                              <p className="text-xl text-gray-600">
                                {currentSlide.content[0] || 'Sottitolo della slide'}
                              </p>
                            </div>
                          )}

                          {currentSlide.type === 'content' && (
                            <div>
                              <h2 className="text-3xl font-bold text-gray-900 mb-6">
                                {currentSlide.title || 'Titolo della Slide'}
                              </h2>
                              <div className="space-y-4">
                                {currentSlide.content.map((paragraph, index) => (
                                  <p key={index} className="text-gray-700 leading-relaxed">
                                    {paragraph || `Contenuto della slide ${index + 1}`}
                                  </p>
                                ))}
                              </div>
                            </div>
                          )}

                          {currentSlide.type === 'bullet' && (
                            <div>
                              <h2 className="text-3xl font-bold text-gray-900 mb-6">
                                {currentSlide.title || 'Titolo della Slide'}
                              </h2>
                              <ul className="space-y-3">
                                {currentSlide.content.map((bullet, index) => (
                                  <li key={index} className="flex items-start">
                                    <span className="text-purple-600 mr-3">•</span>
                                    <span className="text-gray-700">
                                      {bullet || `Punto elenco ${index + 1}`}
                                    </span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}

                          {currentSlide.type === 'quote' && (
                            <div className="text-center">
                              <blockquote className="text-2xl italic text-gray-700 mb-6">
                                "{currentSlide.content[0] || 'Citazione importante'}"
                              </blockquote>
                              <p className="text-gray-600">
                                {currentSlide.title || 'Autore della citazione'}
                              </p>
                            </div>
                          )}

                          {currentSlide.type === 'image' && (
                            <div>
                              <h2 className="text-3xl font-bold text-gray-900 mb-6 text-center">
                                {currentSlide.title || `Slide ${currentSlideIndex + 1}`}
                              </h2>
                              <div className="flex justify-center">
                                {currentSlide.content && currentSlide.content[0] && (
                                  (() => {
                                    const url = currentSlide.content[0];
                                    if (url.startsWith('data:application/pdf;base64,')) {
                                      // Handle PDF slides
                                      return (
                                        <div className="w-full max-w-2xl mx-auto bg-white rounded-lg shadow-lg p-4">
                                          <div className="text-center mb-2">
                                            <span className="text-sm text-gray-600">📄 Documento PDF</span>
                                          </div>
                                          <div className="border rounded p-3 bg-gray-50 text-center">
                                            <p className="text-sm text-gray-700">
                                              {currentSlide.title || `Slide ${currentSlideIndex + 1}`}
                                            </p>
                                            <p className="text-xs text-gray-500 mt-1">
                                              PDF con contenuti strutturati
                                            </p>
                                            <a
                                              href={url}
                                              download={`slide_${currentSlideIndex + 1}.pdf`}
                                              className="inline-block mt-2 px-3 py-1 bg-blue-600 text-white text-sm rounded hover:bg-blue-700"
                                            >
                                              Download PDF
                                            </a>
                                          </div>
                                        </div>
                                      );
                                    } else if (url.startsWith('data:text/html;base64,')) {
                                      // Handle HTML slides (fallback)
                                      const htmlContent = atob(url.split(',')[1]);
                                      return (
                                        <iframe
                                          srcDoc={htmlContent}
                                          className="w-full h-96 border rounded-lg shadow-lg"
                                          title={currentSlide.title}
                                          sandbox="allow-same-origin"
                                        />
                                      );
                                    } else {
                                      // Handle regular images
                                      return (
                                        /* eslint-disable-next-line @next/next/no-img-element */
                                        <img
                                          src={url}
                                          alt={currentSlide.title}
                                          className="max-w-full max-h-96 rounded-lg shadow-lg"
                                          onError={(e) => {
                                            e.currentTarget.src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJDNi40NzcgMiAyIDYuNDc3IDIgMTJDNi40NzcgMjIgMTIgMjJDMTcuNTIzIDIyIDIyIDE3LjUyMyAyMiAxMkMyMjA2LjQ3NyAxNy41MjMgMiAxMiAyWiIgc3Ryb2tlPSIjRDFERUQ0IiBzdHyb2tlLXdpZHRoPSIjIiLz4KPHA+SW1hZ2UgY2Fubm90IGJlIGRpc3BsYXllZDwvcD4KPC9zdmc+';
                                          }}
                                        />
                                      );
                                    }
                                  })()
                                ) || (
                                  <div className="bg-gray-200 rounded-lg h-96 w-full flex items-center justify-center">
                                    <span className="text-gray-500">Contenuto non disponibile</span>
                                  </div>
                                )}
                              </div>
                              {currentSlide.notes && (
                                <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-lg text-center">
                                  <div className="text-sm text-blue-700">{currentSlide.notes}</div>
                                </div>
                              )}
                            </div>
                          )}
                        </div>

                        {/* Slide Notes */}
                        {currentSlide.notes && (
                          <div className="mt-4 p-3 bg-yellow-50 border border-yellow-200 rounded-lg">
                            <div className="text-sm font-medium text-yellow-800 mb-1">Note:</div>
                            <div className="text-sm text-yellow-700">{currentSlide.notes}</div>
                          </div>
                        )}
                      </div>
                    )}

                    {/* Slide Navigation */}
                    <div className="flex justify-center mt-6 space-x-2">
                      {currentPresentation.slides.map((_, index) => (
                        <button
                          key={index}
                          onClick={() => setCurrentSlideIndex(index)}
                          className={`w-2 h-2 rounded-full transition-all ${
                            index === currentSlideIndex
                              ? 'bg-purple-600 w-8'
                              : 'bg-gray-300 hover:bg-gray-400'
                          }`}
                        />
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="bg-white rounded-xl shadow-sm border p-12 text-center">
                <FileText className="w-16 h-16 text-gray-400 mx-auto mb-4" />
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  Nessuna Presentazione Selezionata
                </h3>
                <p className="text-gray-600 mb-6">
                  Genera una nuova presentazione o selezionane una esistente per iniziare.
                </p>
                <div className="max-w-md mx-auto">
                  <div className="grid grid-cols-2 gap-4 text-left">
                    <div className="p-4 bg-purple-50 rounded-lg">
                      <div className="text-purple-600 font-medium mb-2">🎨 Temi Personalizzabili</div>
                      <div className="text-sm text-gray-700">Scegli tra diversi temi per adattare lo stile alle tue esigenze</div>
                    </div>
                    <div className="p-4 bg-blue-50 rounded-lg">
                      <div className="text-blue-600 font-medium mb-2">🤝 AI-Powered</div>
                      <div className="text-sm text-gray-700">Generazione automatica basata sui tuoi materiali di studio</div>
                    </div>
                    <div className="p-4 bg-green-50 rounded-lg">
                      <div className="text-green-600 font-medium mb-2">📝 Modifica Facile</div>
                      <div className="text-sm text-gray-700">Modifica e personalizza ogni slide secondo le tue necessità</div>
                    </div>
                    <div className="p-4 bg-orange-50 rounded-lg">
                      <div className="text-orange-600 font-medium mb-2">🚀 Export Veloce</div>
                      <div className="text-sm text-gray-700">Esporta le presentazioni in vari formati</div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
